services:
  prod:
    build:
      context: .
      dockerfile: ./docker/images/node/Dockerfile
      target: prod
    profiles:
      - optional
  node:
    build:
      context: .
      dockerfile: ./docker/images/node/Dockerfile
    image: node:lts
    working_dir: /app/code
    hostname: ${PROJECT_PREFIX}
    container_name: ${PROJECT_PREFIX}
    volumes:
      - ./docker/config/dev/ssh:/root/.ssh/
      - ./docker/config/dev/git/.gitconfig:/root/.gitconfig
      - ./docker/config/dev/node/init-script.sh:/root/init-script.sh
      - .:/app
    ports:
      - ${WEB_PORT}:4000
    command: sh /root/init-script.sh
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}

  dist-dev:
    build:
      context: .
      dockerfile: ./docker/images/node/Dockerfile
      target: dist-dev
    container_name: ${PROJECT_PREFIX}-dist-dev
    hostname: ${PROJECT_PREFIX}-dist-dev
    ports:
      - ${DIST_PORT_WEB_PORT}:4000
      - ${DIST_PORT_MONGO_PORT}:27017
    profiles:
      - dist

volumes:
  mongo-data:
