services:
  node:
    build:
      context: .
      dockerfile: ./docker/images/node/Dockerfile
    image: node:lts
    working_dir: /app/code
    hostname: ${PROJECT_PREFIX}
    container_name: ${PROJECT_PREFIX}
    volumes:
      - ./docker/config/dev/ssh:/root/.ssh/
      - ./docker/config/dev/git/.gitconfig:/root/.gitconfig
      - .:/app
    ports:
      - ${WEB_PORT}:3000
    command: tail -f /dev/null
    env_file:
      - .env
    networks:
      - default

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=chateroen
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    networks:
      - default
volumes:
  mongo-data:

networks:
  default:
    external: true
    name: ${PROJECT_NETWORK}